import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const artifact=path.resolve(fileURLToPath(new URL('../../artifacts/',import.meta.url)));
await mkdir(artifact,{recursive:true});
const base='http://127.0.0.1:8001/portal-api',origin='http://127.0.0.1:5174';
const login=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'admin',password:'fixture-admin-password-long'})});
assert.equal(login.status,200);
const cookie=login.headers.get('set-cookie').split(';')[0],csrf=(await login.json()).csrf;
async function admin(url,body){const response=await fetch(base+url,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});assert(response.ok,`Admin request failed: ${url}, ${response.status}`);return response.json();}
const username='browser'+Date.now()+'@qq.com';
await admin('/admin/keys/import',{keys:['sk-browser-fixture-aaaa'+Date.now(),'sk-browser-fixture-bbbb'+Date.now()]});
const invite=(await admin('/admin/invites',{max_uses:1})).code;
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAIAAAADnC86AAAATElEQVR4nO3NsQHAMAzDMIf//+yu0QPMUOEBnN2dF3iyTmMRZnZrrMGrUmMNXpUaa/Cq1FiDV6XGGrwqNdbgVamxBq9KjTV41fw8/gCD6wNNCJl4CAAAAABJRU5ErkJggg==','base64');
const qr=new FormData();qr.append('file',new Blob([image],{type:'image/png'}),'test.png');
const upload=await fetch(base+'/admin/payment-qr/wechat',{method:'POST',headers:{Cookie:cookie,'X-CSRF-Token':csrf},body:qr});assert.equal(upload.status,200);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const context=await browser.newContext({viewport:{width:1440,height:980},acceptDownloads:true});
const page=await context.newPage(),errors=[];
try {
page.on('pageerror',e=>errors.push(e.message));
await page.goto(origin);await page.getByRole('heading',{name:'欢迎回来'}).waitFor();
await page.screenshot({path:path.join(artifact,'website-login.png'),fullPage:true});
await page.getByRole('button',{name:'邀请码注册',exact:true}).click();
await page.getByLabel('用户名或邮箱',{exact:true}).fill(username);
await page.getByLabel('怎么称呼你').fill('小林（测试账号）');
await page.getByLabel('密码',{exact:true}).fill('fixture-student-password');
await page.getByLabel('邀请码',{exact:true}).fill(invite);
await page.getByRole('button',{name:'创建账户',exact:true}).click();
await page.getByRole('heading',{name:'小林（测试账号），开始创造吧。'}).waitFor();
await page.getByRole('button',{name:'充值',exact:true}).click();
await page.locator('input[type=checkbox]').check();
await page.getByRole('button',{name:'生成充值订单',exact:true}).click();
await page.getByRole('button',{name:'我已付款，提交审核'}).waitFor();
await page.getByRole('button',{name:'我已付款，提交审核'}).click();
await page.getByText('付款声明已提交，等待管理员核实到账',{exact:true}).waitFor();
const order=(await admin('/admin/orders')).find(o=>o.username===username);
await admin(`/admin/orders/${order.id}/review`,{action:'approve'});
await page.getByRole('button',{name:'概览',exact:true}).click();await page.getByTitle('刷新数据').click();
await page.locator('.big-money').filter({hasText:'¥19.00'}).waitFor();
await page.screenshot({path:path.join(artifact,'website-dashboard.png'),fullPage:true});
await page.getByRole('button',{name:'安装助手',exact:true}).click();
await page.getByLabel('DeepSeek Harness',{exact:false}).check();
const downloadWait=page.waitForEvent('download');await page.getByRole('button',{name:'下载我的 Windows 安装助手'}).click();
const download=await downloadWait;await download.saveAs(path.join(artifact,'browser-test-installer.zip'));
await page.screenshot({path:path.join(artifact,'website-download.png'),fullPage:true});

await page.getByRole('button',{name:'邀请好友',exact:true}).click();
await page.getByRole('button',{name:'生成邀请码',exact:true}).click();
await page.locator('.member-invite-created>code').waitFor();
const memberCode=await page.locator('.member-invite-created>code').innerText();
assert.match(memberCode,/^CA-[A-F0-9]{16}$/);
const invitedContext=await browser.newContext(),invitedPage=await invitedContext.newPage();
await invitedPage.goto(origin+'/login?invite='+memberCode);
await invitedPage.getByRole('heading',{name:'加入学院工作区'}).waitFor();
assert.equal(await invitedPage.getByLabel('邀请码',{exact:true}).inputValue(),memberCode);
await invitedContext.close();
await page.locator('tbody').getByRole('button',{name:'停用',exact:true}).first().click();
await page.locator('tbody').getByText('已停用',{exact:true}).waitFor();
await page.screenshot({path:path.join(artifact,'website-member-invites.png'),fullPage:true});
await page.getByRole('button',{name:'安装助手',exact:true}).click();

const student=(await admin('/admin/users')).find(u=>u.username===username);
await admin(`/admin/users/${student.id}/action`,{action:'block'});
await page.getByTitle('刷新数据').click();
await page.waitForFunction(()=>document.querySelector('.download-feature button').disabled);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifact,'website-mobile.png'),fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile layout overflows');
const adminContext=await browser.newContext({viewport:{width:1440,height:1000}}),adminPage=await adminContext.newPage();
adminPage.on('pageerror',e=>errors.push(e.message));
await adminPage.goto(origin);await adminPage.getByLabel('用户名或邮箱',{exact:true}).fill('admin');await adminPage.getByLabel('密码',{exact:true}).fill('fixture-admin-password-long');
await adminPage.getByRole('button',{name:'登录工作区'}).click();
await adminPage.getByRole('button',{name:'安装助手',exact:true}).click();
await adminPage.getByText('当前账户尚未分配 Key，仍可下载并安装软件。',{exact:false}).waitFor();
await adminPage.getByLabel('Claude Code',{exact:false}).uncheck();
assert(await adminPage.getByRole('button',{name:'下载我的 Windows 安装助手'}).isDisabled(),'Empty tool selection must be disabled');
await adminPage.getByLabel('DeepSeek Harness',{exact:false}).check();
assert(await adminPage.getByRole('button',{name:'下载我的 Windows 安装助手'}).isEnabled(),'Keyless administrator download must be enabled');
const keylessDownloadWait=adminPage.waitForEvent('download');
await adminPage.getByRole('button',{name:'下载我的 Windows 安装助手'}).click();
await (await keylessDownloadWait).saveAs(path.join(artifact,'browser-keyless-harness.zip'));
await adminPage.screenshot({path:path.join(artifact,'website-keyless-download.png'),fullPage:true});
await adminPage.getByRole('button',{name:'管理工作台',exact:true}).click();
await adminPage.getByRole('heading',{name:'库存与停用待办'}).waitFor();
await adminPage.getByRole('cell').filter({hasText:'小林（测试账号）'}).first().waitFor();
await adminPage.screenshot({path:path.join(artifact,'website-admin.png'),fullPage:true});
for(const tab of ['收款审核','账户管理','消费核对','邀请码','渠道','设置与公告','操作记录']){await adminPage.locator('.admin-tabs').getByRole('button',{name:tab,exact:true}).click();await adminPage.waitForTimeout(180);}

await adminPage.getByRole('button',{name:'账户管理',exact:true}).first().click();
await adminPage.getByRole('heading',{name:'账户管理',exact:true}).waitFor();
await adminPage.getByRole('button',{name:'新建用户',exact:true}).click();
let dialog=adminPage.getByRole('dialog',{name:'新建用户'});
const managed='managed'+Date.now()+'@qq.com';
await dialog.getByLabel('用户名或邮箱',{exact:true}).fill(managed);
await dialog.getByLabel('用户称呼').fill('后台测试成员');
await dialog.getByLabel('初始密码').fill('fixture-managed-password');
await dialog.getByRole('button',{name:'保存账户'}).click();
await dialog.waitFor({state:'hidden'});
await adminPage.getByLabel('搜索用户').fill(managed);
let row=adminPage.locator('tbody tr').filter({hasText:managed});
await row.getByRole('button',{name:'编辑账户'}).click();
dialog=adminPage.getByRole('dialog',{name:'编辑账户'});
await dialog.getByLabel('用户称呼').fill('已编辑测试成员');
await dialog.getByRole('button',{name:'保存账户'}).click();await dialog.waitFor({state:'hidden'});
await row.filter({hasText:'已编辑测试成员'}).waitFor();
await row.getByRole('button',{name:'重置密码'}).click();
dialog=adminPage.getByRole('dialog',{name:'重置用户密码'});
await dialog.getByLabel('新密码').fill('fixture-managed-new-password');
await dialog.getByRole('button',{name:'确认重置密码'}).click();await dialog.waitFor({state:'hidden'});
await adminPage.getByRole('button',{name:'官方 Key 号池',exact:true}).first().click();
await adminPage.getByRole('heading',{name:'官方 API Key 号池'}).waitFor();
const poolKey='sk-ui-pool-fixture-'+Date.now();
await adminPage.locator('input[type=file]').setInputFiles({name:'keys.txt',mimeType:'text/plain',buffer:Buffer.from(poolKey+'\n'+poolKey)});
await adminPage.getByText('重复行 1 个',{exact:true}).waitFor();
await adminPage.getByRole('button',{name:'加密导入号池'}).click();
await adminPage.getByText('新增 1 个，跳过 0 个已有 Key',{exact:true}).waitFor();
const targetKey=(await admin('/admin/keys')).find(k=>k.masked.endsWith(poolKey.slice(-4)));
assert(targetKey && targetKey.status==='available');
row=adminPage.locator('tbody tr').filter({hasText:targetKey.masked});
await row.getByRole('button',{name:'停用库存'}).click();await row.getByRole('button',{name:'启用库存'}).waitFor();
await row.getByRole('button',{name:'启用库存'}).click();await row.getByRole('button',{name:'停用库存'}).waitFor();
const waiting=(await admin('/admin/users')).filter(u=>u.role==='student'&&u.status==='active'&&!['assigned','pending_revocation'].includes(u.key_status));
if(!waiting.length){await admin('/admin/keys/'+targetKey.id+'/inventory',{action:'disable'});await admin('/admin/users',{username:'wait'+Date.now(),display_name:'指定分配测试',password:'fixture-waiting-password'});await admin('/admin/keys/'+targetKey.id+'/inventory',{action:'enable'});await adminPage.getByRole('button',{name:'刷新号池'}).click();}
await row.getByRole('button',{name:'指定用户分配'}).click();dialog=adminPage.getByRole('dialog',{name:'指定用户分配 Key'});
await dialog.getByRole('button',{name:'确认分配'}).click();await dialog.waitFor({state:'hidden'});
await row.getByText('已分配',{exact:true}).waitFor();
await adminPage.screenshot({path:path.join(artifact,'website-admin-pool.png'),fullPage:true});
await adminPage.getByRole('button',{name:'账户管理',exact:true}).first().click();
await adminPage.getByRole('heading',{name:'账户管理',exact:true}).waitFor();
await adminPage.screenshot({path:path.join(artifact,'website-admin-accounts.png'),fullPage:true});
await adminPage.setViewportSize({width:390,height:844});
assert(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile management layout overflows');

assert.deepEqual(errors,[]);
} finally { await browser.close(); }
await writeFile(path.join(artifact,'browser-checks.json'),JSON.stringify({passed:true,checks:['invite registration','payment claim and approval','reconciled dashboard','installer ZIP download','blocked delivery','mobile layout','all admin tabs','email registration','account create edit reset','TXT key pool import','inventory enable disable','specific assignment','member invitation generation and disable','invite URL prefilling'],pageErrors:errors},null,2));
console.log('PASS: browser registration, payment, dashboard, download, suspension, mobile layout, admin tabs, email registration, accounts, and key pool management.');
