import {useMemo, useState, type FormEvent, type ReactNode} from 'react';
import {FileUp, Plus, RefreshCw, Search, ShieldCheck, X} from 'lucide-react';
import {api} from './api';

type Row = Record<string, any>;
type Action = (fn: () => Promise<any>, message?: string) => Promise<any>;
const money = (value = 0) => '¥' + (value / 100).toFixed(2);
const date = (value?: number) => value ? new Date(value * 1000).toLocaleString('zh-CN', {hour12: false}) : '未设置';
const labels: Record<string, string> = {available: '可分配', assigned: '已分配', disabled: '库存已停用', pending_revocation: '待官网撤销', revoked: '已核验不可用', active: '正常', blocked: '已暂停领取'};
const badge = (value: string) => <span className={'badge ' + (['active', 'assigned'].includes(value) ? 'good' : ['blocked', 'pending_revocation'].includes(value) ? 'warn' : 'neutral')}>{labels[value] || value}</span>;
function Box({title, caption, action, children}: {title: string; caption?: string; action?: ReactNode; children: ReactNode}) {
  return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{caption && <p>{caption}</p>}</div>{action}</div>{children}</section>;
}
function Modal({title, close, children}: {title: string; close: () => void; children: ReactNode}) {
  return <div className="management-overlay" onClick={close}><section className="management-dialog" role="dialog" aria-modal="true" aria-label={title} onClick={e => e.stopPropagation()}><div className="panel-head"><h2>{title}</h2><button type="button" className="icon-button" aria-label="关闭窗口" onClick={close}><X size={18}/></button></div>{children}</section></div>;
}

export function AdminAccounts({rows, providers, busy, act}: {rows: Row[]; providers: Row[]; busy: boolean; act: Action}) {
  const [search, setSearch] = useState(''), [state, setState] = useState('all'), [editing, setEditing] = useState<Row | null>(null), [resetting, setResetting] = useState<Row | null>(null);
  const visible = rows.filter(u => (!search || (u.username + ' ' + u.display_name).toLowerCase().includes(search.toLowerCase())) && (state === 'all' || u.status === state));
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const body = Object.fromEntries(new FormData(event.currentTarget));
    const result = await act(() => editing?.id ? api('/admin/users/' + editing.id, 'PATCH', body) : api('/admin/users', 'POST', body), editing?.id ? '账户信息已更新' : '用户账户已创建');
    if (result) setEditing(null);
  }
  return <><Box title="账户管理" caption="新建成员账户、编辑登录名、重置密码及管理配置领取。管理员账户受到保护。" action={<button className="primary" disabled={busy} onClick={() => setEditing({})}><Plus size={16}/>新建用户</button>}>
    <div className="management-toolbar"><label className="management-search"><Search size={16}/><input aria-label="搜索用户" placeholder="搜索用户名、邮箱或称呼" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="筛选账户状态" value={state} onChange={e => setState(e.target.value)}><option value="all">全部状态</option><option value="active">正常</option><option value="blocked">已暂停领取</option></select><span>{visible.length} 个账户</span></div>
    <div className="table-wrap"><table><thead><tr><th>用户 / 登录名</th><th>账户状态</th><th>官方 Key</th><th>已购 / 已核对余额</th><th>操作</th></tr></thead><tbody>{visible.map(u => <tr key={u.id}><td>{u.display_name}<small>{u.username}</small><small>注册于 {date(u.created_at)}</small></td><td>{u.role === 'admin' ? <span className="badge good">管理员</span> : badge(u.status)}</td><td>{u.key_masked ? <><code>{u.key_masked}</code><small>{labels[u.key_status] || u.key_status}</small></> : <span className="badge warn">等待分配</span>}</td><td>{money(u.purchased_fen)}<small>{money(u.reconciled_fen)}</small></td><td>{u.role !== 'admin' && <div className="table-actions"><button className="text-link" disabled={busy} onClick={() => setEditing(u)}>编辑账户</button><button className="text-link" disabled={busy} onClick={() => setResetting(u)}>重置密码</button><select aria-label={'分配渠道：' + u.username} id={'account-provider-' + u.id}>{providers.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="small-button" disabled={busy} onClick={() => act(() => api(`/admin/users/${u.id}/action`, 'POST', {action: u.status === 'blocked' ? 'activate' : 'assign', provider_id: Number((document.getElementById('account-provider-' + u.id) as HTMLSelectElement).value)}))}>{u.status === 'blocked' ? '恢复领取' : '分配 Key'}</button>{u.status !== 'blocked' && <button className="text-link danger-text" disabled={busy} onClick={() => {if (confirm('暂停该用户领取配置？已发官方 Key 需要在官网删除后核验。')) act(() => api(`/admin/users/${u.id}/action`, 'POST', {action: 'block'}));}}>暂停领取</button>}</div>}</td></tr>)}</tbody></table></div>{!visible.length && <p className="management-empty">没有匹配账户。可新建用户，也可通过邀请码邀请注册。</p>}
  </Box>
  {editing && <Modal title={editing.id ? '编辑账户' : '新建用户'} close={() => !busy && setEditing(null)}><form onSubmit={save}><label>用户名或邮箱<input name="username" defaultValue={editing.username || ''} minLength={3} maxLength={128} required autoComplete="off" placeholder="例如 student 或 student@qq.com"/></label><label>用户称呼<input name="display_name" defaultValue={editing.display_name || ''} maxLength={40} required/></label>{!editing.id && <label>初始密码<input type="password" name="password" minLength={8} maxLength={128} autoComplete="new-password" required/></label>}<p>{editing.id ? '修改登录名后，该用户需重新登录。' : '创建成员账户，无需消耗邀请码；库存充足时自动分配 Key。'}</p><button className="primary full" disabled={busy} type="submit">{busy ? '正在保存…' : '保存账户'}</button></form></Modal>}
  {resetting && <Modal title="重置用户密码" close={() => !busy && setResetting(null)}><form onSubmit={async e => {e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); const result = await act(() => api(`/admin/users/${resetting.id}/password`, 'POST', body)); if (result) setResetting(null);}}><p>账户：{resetting.username}。重置后旧登录会话和未使用的安装票据失效；已发出的官方 Key 保持原状态。</p><label>新密码<input type="password" name="password" minLength={8} maxLength={128} autoComplete="new-password" required/></label><button className="primary full" type="submit" disabled={busy}>确认重置密码</button></form></Modal>}
  </>;
}

export function AdminKeyPool({rows, users, providers, busy, act, enabled, refresh, say}: {rows: Row[]; users: Row[]; providers: Row[]; busy: boolean; act: Action; enabled: boolean; refresh: () => Promise<void>; say: (value: string) => void}) {
  const [text, setText] = useState(''), [provider, setProvider] = useState('1'), [search, setSearch] = useState(''), [state, setState] = useState('all'), [assigning, setAssigning] = useState<Row | null>(null), [reading, setReading] = useState(false);
  const parsed = useMemo(() => {const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).map(v => v.trim()).filter(Boolean), unique = [...new Set(lines)]; return {lines, unique, invalid: unique.filter(v => !/^[A-Za-z0-9_.-]{16,200}$/.test(v)).length, duplicates: lines.length - unique.length};}, [text]);
  const visible = rows.filter(k => (state === 'all' || k.status === state) && (!search || (k.masked + ' ' + (k.username || '') + ' ' + k.provider).toLowerCase().includes(search.toLowerCase())));
  const waiting = users.filter(u => u.status === 'active' && !['assigned', 'pending_revocation'].includes(u.key_status));
  async function importFile(file?: File) {if (!file) return; if (file.size > 200_000) {say('文本文件需小于200KB'); return;} setReading(true); try {setText(await file.text());} catch {say('无法读取文件，请使用UTF-8文本文件');} finally {setReading(false);}}
  async function pasteKeys() {try {if (!navigator.clipboard?.readText) throw Error(); setText(await navigator.clipboard.readText());} catch {say('请点击文本框，使用 Ctrl+V 粘贴 Key，或读取 TXT 文件');}}
  return <><Box title="官方 API Key 号池" caption="密钥加密保存、每人独享一个；已发出的 Key 不会重新分配给其他人。" action={<button className="text-link" onClick={() => refresh().catch(e => say(e.message))}><RefreshCw size={14}/>刷新号池</button>}>
    <div className="pool-summary">{[['available', '可分配库存'], ['assigned', '已分配'], ['disabled', '已停用库存'], ['pending_revocation', '待官网撤销']].map(([s, label]) => <div key={s}><span>{label}</span><strong>{rows.filter(k => k.status === s).length}</strong></div>)}</div>
    {!enabled && <div className="inline-warning" role="status">当前为 IP 界面验证模式。可信 HTTPS 启用后才能导入真实 Key 和领取安装配置；不会通过明文连接发送密钥。</div>}
    <form onSubmit={async e => {e.preventDefault(); const result = await act(() => api('/admin/keys/import', 'POST', {provider_id: Number(provider), keys: parsed.unique})); if (result) {setText(''); say(`新增 ${result.imported} 个，跳过 ${result.duplicates} 个已有 Key`);}}}>
      <div className="management-toolbar"><label>导入渠道<select aria-label="导入渠道" value={provider} onChange={e => setProvider(e.target.value)}>{providers.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className={'upload-button ' + (!enabled ? 'disabled-upload' : '')}><FileUp size={16}/>{reading ? '读取中…' : '读取 TXT 文件'}<input type="file" accept=".txt,text/plain" disabled={!enabled || reading} onChange={e => {importFile(e.target.files?.[0]); e.target.value = '';}}/></label></div>
      <button className="text-link" type="button" disabled={!enabled || busy} onClick={pasteKeys}>从剪贴板粘贴 Key</button>
      <label>批量 API Key<textarea name="keys" aria-label="批量 API Key" rows={5} value={text} onChange={e => setText(e.target.value)} placeholder={enabled ? '每行一个 API Key，或选择 UTF-8 TXT 文件' : '可信 HTTPS 启用后可导入官方 API Key'} autoComplete="off" spellCheck={false} disabled={!enabled}/></label>
      <div className="import-preview"><span>待导入 {parsed.unique.length} 个</span><span>重复行 {parsed.duplicates} 个</span><span className={parsed.invalid ? 'danger-text' : ''}>格式异常 {parsed.invalid} 个</span></div><button className="primary" type="submit" disabled={!enabled || busy || reading || !parsed.unique.length || !!parsed.invalid || parsed.unique.length > 500}><ShieldCheck size={16}/>{busy ? '正在导入…' : '加密导入号池'}</button><p>单次最多500个。导入 DeepSeek 库存后，自动为等待分配的正常账户分配配置。导入不会查询官方余额。</p>
    </form>
  </Box>
  <Box title="库存与停用待办" caption="停用未分配库存只阻止分配；已发官方 Key 必须先在官网删除，再核验。">
    <div className="management-toolbar"><label className="management-search"><Search size={16}/><input aria-label="搜索号池" placeholder="搜索密钥尾号、用户名或渠道" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="筛选号池状态" value={state} onChange={e => setState(e.target.value)}><option value="all">全部状态</option>{Object.entries(labels).filter(([s]) => !['active', 'blocked'].includes(s)).map(([s, label]) => <option value={s} key={s}>{label}</option>)}</select><span>{visible.length} 条记录</span></div>
    <div className="table-wrap"><table><thead><tr><th>Key / 渠道</th><th>归属</th><th>状态</th><th>截止提醒</th><th>操作</th></tr></thead><tbody>{visible.map(k => <tr key={k.id}><td><code>{k.masked}</code><small>{k.provider}</small></td><td>{k.display_name || '尚未分配'}<small>{k.username}</small></td><td>{badge(k.status)}{k.last_verification && <small>{k.last_verification === 'still_valid' ? '官方 Key 仍有效' : k.last_verification === 'revoked' ? '鉴权已失效' : '待核实'}</small>}</td><td>{date(k.expires_at)}</td><td><div className="table-actions">{k.status === 'available' && <><button className="small-button" disabled={busy || !waiting.length} onClick={() => setAssigning(k)}>指定用户分配</button><button className="text-link" disabled={busy} onClick={() => act(() => api(`/admin/keys/${k.id}/inventory`, 'POST', {action: 'disable'}), '已停止分配此库存 Key')}>停用库存</button></>}{k.status === 'disabled' && <button className="text-link" disabled={busy} onClick={() => act(() => api(`/admin/keys/${k.id}/inventory`, 'POST', {action: 'enable'}), '此 Key 已重新加入可分配库存')}>启用库存</button>}{k.status === 'assigned' && <><button className="text-link" disabled={busy} onClick={() => {const input = prompt('截止提醒时间，例如 2026-11-01T18:00；留空清除'); if (input === null) return; const stamp = input ? Date.parse(input) : NaN; if (input && !Number.isFinite(stamp)) {say('时间格式不正确'); return;} act(() => api(`/admin/keys/${k.id}/deadline`, 'POST', {expires_at: input ? Math.floor(stamp / 1000) : null}));}}>设置提醒</button><button className="text-link danger-text" disabled={busy} onClick={() => {if (confirm('暂停领取并生成官网撤销待办？已发的官方 Key 不会因此失效。')) act(() => api(`/admin/users/${k.owner_id}/action`, 'POST', {action: 'block'}));}}>暂停领取</button></>}{k.status === 'pending_revocation' && <><a href="https://platform.deepseek.com/api_keys" target="_blank" rel="noreferrer">官网删除</a><button className="small-button" disabled={busy} onClick={() => act(() => api(`/admin/keys/${k.id}/verify-revocation`, 'POST'))}>核验停用</button></>}</div></td></tr>)}</tbody></table></div>{!visible.length && <p className="management-empty">暂无匹配的 Key。导入官方 Key 后可查看库存和分配记录。</p>}
  </Box>
  {assigning && <Modal title="指定用户分配 Key" close={() => !busy && setAssigning(null)}><form onSubmit={async e => {e.preventDefault(); const values = new FormData(e.currentTarget); const result = await act(() => api(`/admin/keys/${assigning.id}/assign`, 'POST', {user_id: Number(values.get('user_id'))}), '已为指定用户分配 Key'); if (result) setAssigning(null);}}><p>库存 Key：{assigning.masked}</p><label>等待分配的用户<select name="user_id" required>{waiting.map(u => <option key={u.id} value={u.id}>{u.display_name} · {u.username}</option>)}</select></label><button className="primary full" type="submit" disabled={busy || !waiting.length}>确认分配</button></form></Modal>}
  </>;
}
