import {useEffect,useState,useRef, type FormEvent, type ReactNode} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,Check,CheckCircle2,ChevronRight,Clipboard,Code2,CreditCard,Download,ExternalLink,FileText,Home,Info,KeyRound,Layers,Loader2,LogOut,Menu,Plus,RefreshCw,ShieldCheck,SlidersHorizontal,Terminal,Users,X,AlertCircle,Clock3} from 'lucide-react';
import {api,setCsrf} from './api';
import {AdminAccounts, AdminKeyPool} from './AdminManagement';
import {MemberInvites} from './MemberInvites';
import {DownloadPage} from './DownloadPage';

type Row=Record<string,any>;
const money=(fen:number=0)=>'¥'+(fen/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(t?:number|null)=>t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'尚未核对';
const labels:Record<string,string>={available:'待分配',assigned:'已分配',pending_revocation:'待官网撤销',revoked:'已核验不可用',pending_payment:'待付款',submitted:'待审核',approved:'已确认',rejected:'已驳回',cancelled:'已取消',active:'正常',blocked:'已暂停领取',still_valid:'官方Key仍有效',uncertain:'待核实'};
const status=(value:string)=><span className={'badge '+(['assigned','approved','active','revoked'].includes(value)?'good':['pending_revocation','submitted','blocked','uncertain'].includes(value)?'warn':'neutral')}>{labels[value]||value}</span>;
function Empty({text='暂时没有记录',detail='完成相关操作后，记录会显示在这里。'}:{text?:string;detail?:string}){return <div className="empty"><Layers size={30}/><h3>{text}</h3><p>{detail}</p></div>}
function Button({children,busy=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{busy?:boolean}){return <button {...props} disabled={busy||props.disabled}>{busy&&<Loader2 size={16} className="spin"/>}{children}</button>}
function Notice({children}:{children:ReactNode}){return <div className="notice"><Info size={17}/><div>{children}</div></div>}
function Panel({title,caption,children,action}:{title:string;caption?:string;children:ReactNode;action?:ReactNode}){return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{caption&&<p>{caption}</p>}</div>{action}</div>{children}</section>}

export function App(){
  const [user,setUser]=useState<Row|null>(null),[pub,setPub]=useState<Row>({settings:{},announcements:[]}),[loaded,setLoaded]=useState(false),[path,setPath]=useState(location.pathname),[toast,setToast]=useState(''),[menu,setMenu]=useState(false);
  const say=(message:string)=>setToast(message);
  const navigate=(to:string)=>{history.pushState({},'',to);setPath(to);setMenu(false);window.scrollTo(0,0);};
  const refresh=async()=>{const row=await api<Row>('/me');setCsrf(row.csrf);setUser(row);};
  const refreshPublic=async()=>setPub(await api('/public'));
  useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);Promise.all([refreshPublic(),refresh().catch(()=>setUser(null))]).catch(e=>say(e.message)).finally(()=>setLoaded(true));return()=>window.removeEventListener('popstate',pop)},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer)},[toast]);
  useEffect(()=>{document.title=pub.settings.site_name||'学院 AI Coding'},[pub]);
  const run=async(task:()=>Promise<unknown>,message?:string)=>{try{await task();if(message)say(message);}catch(e){say((e as Error).message)}};
  const copy=async(text:string)=>run(async()=>{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return;}const input=document.createElement('textarea');input.value=text;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();try{if(!document.execCommand('copy'))throw new Error('复制失败，请选中邀请码手动复制');}finally{input.remove()}},'已复制');
  if(!loaded)return <div className="loading-screen"><Code2/><span>正在连接学院 AI Coding…</span></div>;
  const authDone=async()=>{await refresh();navigate('/dashboard')};
  if(!user)return <><Login siteName={pub.settings.site_name||'学院 AI Coding'} onDone={authDone} say={say}/>{toast&&<div role="alert" className="toast"><AlertCircle size={18}/>{toast}<button onClick={()=>setToast('')} aria-label="关闭"><X size={16}/></button></div>}</>;
  const routes=[['/dashboard','概览',Home],['/recharge','充值',CreditCard],['/usage','消费记录',FileText],['/download','安装助手',Download],['/invite','邀请好友',Users],['/docs','使用指南',Terminal]] as const;
  const current=path.startsWith('/admin')?'管理工作台':routes.find(r=>r[0]===path)?.[1]||'概览';
  return <div className="app-shell">
    <aside className={'sidebar '+(menu?'open':'')}><a className="brand" href="/dashboard" onClick={e=>{e.preventDefault();navigate('/dashboard')}}><span className="brand-mark"><Code2 size={22}/></span><div>{pub.settings.site_name||'学院 AI Coding'}<small>CAMPUS WORKSPACE</small></div></a><div className="nav-label">我的工作区</div><nav>{routes.map(([url,title,Icon])=><button key={url} className={path===url?'active':''} onClick={()=>navigate(url)}><Icon size={19}/>{title}{path===url&&<ChevronRight size={15}/>}</button>)}{user.role==='admin'&&<><div className="nav-label admin-label">平台管理</div><button className={path==='/admin'?'active':''} onClick={()=>navigate('/admin')}><SlidersHorizontal size={19}/>管理工作台</button><button className={path==='/admin/users'?'active':''} onClick={()=>navigate('/admin/users')}><Users size={19}/>账户管理</button><button className={path==='/admin/keys'?'active':''} onClick={()=>navigate('/admin/keys')}><KeyRound size={19}/>官方 Key 号池</button></>}</nav><div className="sidebar-bottom"><div className="direct-note"><ShieldCheck size={19}/><div>官方直连<small>模型流量直达 DeepSeek</small></div></div><button className="account" onClick={()=>run(async()=>{await api('/auth/logout','POST');setUser(null);setCsrf('');navigate('/login')})}><span className="avatar">{user.display_name.slice(0,1)}</span><div>{user.display_name}<small>{user.role==='admin'?'管理员':'学院成员'}</small></div><LogOut size={17}/></button></div></aside>
    {menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}
    <div className="workspace"><header className="topbar"><div><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="展开菜单"><Menu size={21}/></button><span className="breadcrumb">工作区 <ChevronRight size={14}/> <strong>{current}</strong></span></div><span className="top-status"><span/>官方直连模式</span></header>
      <main><div className="page-heading"><div><span className="eyebrow">YOUR CODING COMPANION</span><h1>{current}</h1></div><button className="icon-button" title="刷新数据" onClick={()=>run(refresh)}><RefreshCw size={18}/></button></div>
        {path.startsWith('/admin')&&user.role==='admin'?<Admin initialTab={path.split('/')[2]||'keys'} onNavigate={tab=>navigate('/admin/'+tab)} pub={pub} say={say} copy={copy} refreshPublic={refreshPublic}/>:path==='/recharge'?<Recharge pub={pub} say={say} refresh={refresh}/>:path==='/usage'?<Usage/>:path==='/download'?<DownloadPage user={user} pub={pub} say={say}/>:path==='/invite'?<MemberInvites active={user.status==='active'} say={say} copy={copy}/>:path==='/docs'?<Docs/>:<Dashboard user={user} pub={pub} navigate={navigate}/>}
        <footer>学院 AI Coding · 你的代码，连接官方模型。<span>消费数据以人工核对记录为准</span></footer>
      </main>
    </div>{toast&&<div role="alert" className="toast"><Info size={18}/>{toast}<button onClick={()=>setToast('')} aria-label="关闭"><X size={16}/></button></div>}
  </div>;
}

function Login({siteName,onDone,say}:{siteName:string;onDone:()=>Promise<void>;say:(s:string)=>void}){
  const [register,setRegister]=useState(()=>new URLSearchParams(location.search).has('invite')),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));data.username=String(data.username||'').trim();if(register)data.invite_code=String(data.invite_code||'').trim().toUpperCase();try{await api(register?'/auth/register':'/auth/login','POST',data);await onDone()}catch(e){say((e as Error).message)}finally{setBusy(false)}}
  return <div className="login"><div className="login-story"><a className="brand"><span className="brand-mark"><Code2 size={25}/></span>{siteName}</a><div className="login-copy"><span className="eyebrow">LESS SETUP. MORE BUILDING.</span><h1>从一个想法，<br/>到一段好代码。</h1><p>领取你的专属配置，让 AI 成为编程搭档。<br/>安装、配置、连接，一次完成。</p><div className="mini-terminal"><div className="terminal-dots"><i/><i/><i/><span>你的下一个项目</span></div><div><span className="muted">PS ~\my-project&gt;</span> claude<br/><br/><span className="terminal-blue">❯</span> 帮我实现这个想法<br/><span className="muted">  读取项目 · 编写代码 · 验证结果</span><br/><br/><span className="terminal-green">✓</span> Ready to build.</div></div><div className="login-features"><span><ShieldCheck size={16}/>DeepSeek 官方直连</span><span><Download size={16}/>可视化安装助手</span></div></div><small>为学院里的每一个创造者。</small></div><div className="login-form"><div className="login-form-inner"><span className="mobile-brand"><Code2/>{siteName}</span><h2>{register?'加入学院工作区':'欢迎回来'}</h2><p>{register?'使用管理员或熟人提供的邀请码创建账户。':'登录后领取配置，开始你的下一个项目。'}</p><div className="tabs"><button className={!register?'selected':''} onClick={()=>setRegister(false)}>登录</button><button className={register?'selected':''} onClick={()=>setRegister(true)}>邀请码注册</button></div><form onSubmit={submit}><label>用户名或邮箱<input name="username" required minLength={3} maxLength={128} autoComplete="username" placeholder="输入用户名或邮箱，例如 student@qq.com"/></label>{register&&<label>怎么称呼你<input name="display_name" required maxLength={40} placeholder="例如：小林"/></label>}<label>密码<input name="password" type="password" required minLength={8} autoComplete={register?'new-password':'current-password'} placeholder="至少 8 位密码"/></label>{register&&<label>邀请码<input name="invite_code" required defaultValue={new URLSearchParams(location.search).get('invite')||''} placeholder="管理员或熟人分享给你的邀请码"/></label>}<Button className="primary full" busy={busy} type="submit">{register?'创建账户':'登录工作区'}<ArrowRight size={17}/></Button></form><div className="login-hint"><KeyRound size={16}/>采用邀请制，邀请码可向管理员或熟人获取。</div></div></div></div>
}

function Dashboard({user,pub,navigate}:{user:Row;pub:Row;navigate:(path:string)=>void}){
  return <><div className="welcome"><div><h2>{user.display_name}，开始创造吧。</h2><p>你的环境与配置，都在这里。</p></div><span className="date-chip">{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span></div><div className="overview-grid"><section className="balance-panel"><div className="card-label">已购额度 <CreditCard size={18}/></div><div className="big-money">{money(user.purchased_fen)}</div><div className="balance-meta"><span>已核对余额 <strong>{money(user.reconciled_fen)}</strong></span><span>核对至 <strong>{user.checked_through?new Date(user.checked_through*1000).toLocaleDateString():'尚未核对'}</strong></span></div><button onClick={()=>navigate('/recharge')}>充值额度<ArrowUpRight size={17}/></button></section><section className="install-hero"><span className="hero-icon"><Terminal size={25}/></span><div><span className="eyebrow">READY WHEN YOU ARE</span><h2>让 AI 加入你的工作流</h2><p>Git、Node.js、Claude Code 和 CC Switch，<br/>通过一个可视化助手完成安装与配置。</p><button className="primary" onClick={()=>navigate('/download')}>打开安装助手<ArrowRight size={17}/></button></div><div className="hero-code" aria-hidden="true"><span>&lt;/&gt;</span><small>build something<br/>that matters.</small></div></section></div><Notice>已核对余额是人工账务记录，不是官方独立余额。消费不会实时更新，也不会按该余额自动截断直连请求。</Notice><div className="two-columns"><Panel title="你的专属配置" caption="客户端直接连接供应商，官方 Key 保存在你自己的电脑。"><div className="config-row"><span>Key 状态</span>{user.key?status(user.key.status):<span className="badge warn">等待分配</span>}</div><div className="config-row"><span>专属 Key</span><code>{user.key?.masked||'管理员添加库存后自动分配'}</code></div><div className="config-row"><span>模型供应商</span><strong>{user.key?.provider||'DeepSeek 官方'}</strong></div><div className="config-row"><span>当前模型</span><code>{user.key?.model||'待分配'}</code></div>{user.status==='blocked'&&<div className="inline-warning">网站已暂停领取。官方 Key 是否失效，以官网撤销核验为准。</div>}<button className="text-link" onClick={()=>navigate('/docs')}>查看使用指南<ArrowRight size={15}/></button></Panel><Panel title="开始使用" caption="从配置到第一个项目，只需三步。"><div className="steps">{[['领取配置','注册后由平台分配专属官方 Key。'],['安装环境','下载安装包，解压并双击 Start.cmd。'],['开始编程','重新打开终端，输入 claude。']].map(([title,desc],i)=><div className="step" key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></Panel></div>{pub.announcements.length>0&&<Panel title="学院公告">{pub.announcements.map((n:Row)=><article className="announcement" key={n.id}><h3>{n.title}<small>{date(n.created_at)}</small></h3><p>{n.content}</p></article>)}</Panel>}</>
}

function Recharge({pub,say,refresh}:{pub:Row;say:(s:string)=>void;refresh:()=>Promise<void>}){
  const [amount,setAmount]=useState(2000),[method,setMethod]=useState('wechat'),[agree,setAgree]=useState(false),[busy,setBusy]=useState(false),[orders,setOrders]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null);
  const load=()=>api<Row[]>('/orders').then(setOrders);
  useEffect(()=>{load().catch(e=>say(e.message))},[]);
  async function create(){setBusy(true);try{const row=await api<Row>('/orders','POST',{amount_fen:amount,method,accept_policy:agree});setSelected(row);await load()}catch(e){say((e as Error).message)}finally{setBusy(false)}}
  async function paid(id:string){setBusy(true);try{await api(`/orders/${id}/paid`,'POST');say('付款声明已提交，等待管理员核实到账');setSelected(null);await load();await refresh()}catch(e){say((e as Error).message)}finally{setBusy(false)}}
  return <><p className="page-description">手动转账，管理员确认到账后记入已购额度。</p><div className="two-columns recharge-layout"><Panel title="选择充值金额" caption="服务费为支付金额的 5%。"><div className="amount-options">{[1000,2000,5000,10000].map(fen=><button className={fen===amount?'chosen':''} onClick={()=>setAmount(fen)} key={fen}><strong>¥{fen/100}</strong><small>记入 {money(fen*0.95)}</small>{fen===amount&&<CheckCircle2 size={17}/>}</button>)}</div><label>收款方式</label><div className="payment-options"><button className={method==='wechat'?'chosen':''} onClick={()=>setMethod('wechat')}>微信支付</button><button className={method==='alipay'?'chosen':''} onClick={()=>setMethod('alipay')}>支付宝</button></div><div className="price-breakdown"><span>支付金额<strong>{money(amount)}</strong></span><span>服务费 · 5%<strong>{money(amount*0.05)}</strong></span><span className="total">记入已购额度<strong>{money(amount*0.95)}</strong></span></div><label className="check-label"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>我了解 5% 服务费、不提供退款，额度为人工账务记录，不是官方独立余额。</span></label><Button className="primary full" disabled={!agree} busy={busy} onClick={create}>生成充值订单<ArrowRight size={17}/></Button></Panel><Panel title={selected?'完成转账':'充值说明'} caption={selected?'请按照订单金额付款，并填写订单备注。':'请先生成订单，再转账并声明付款。'}>{selected?<><div className="qr-box">{pub.settings[selected.method+'_qr']?<img alt="管理员收款码" src={pub.settings[selected.method+'_qr']}/>:<p>收款码未配置</p>}</div><div className="order-details"><span>需支付<strong>{money(selected.gross_fen)}</strong></span><span>付款备注<code>{selected.id}</code></span></div><p>{pub.settings.payment_note}</p><Button className="primary full" busy={busy} onClick={()=>paid(selected.id)}>我已付款，提交审核</Button></>:<div className="steps">{[['生成订单','选择金额和支付方式。'],['扫码转账','备注完整订单号，便于核对。'],['等待审核','点击“我已付款”不会直接增加额度。']].map(([t,d],i)=><div className="step" key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div>}</Panel></div><Panel title="充值记录" action={<button className="text-link" onClick={()=>load().catch(e=>say(e.message))}>刷新<RefreshCw size={14}/></button>}>{orders.length?<div className="table-wrap"><table><thead><tr><th>订单</th><th>支付金额</th><th>服务费</th><th>记入额度</th><th>状态</th><th>操作</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><code>{o.id}</code><small>{date(o.created_at)}</small></td><td>{money(o.gross_fen)}</td><td>{money(o.fee_fen)}</td><td>{money(o.net_fen)}</td><td>{status(o.status)}</td><td>{o.status==='pending_payment'&&<div className="table-actions"><button className="text-link" onClick={()=>setSelected(o)}>继续付款</button><button className="text-link" onClick={async()=>{if(!confirm('确认尚未付款并取消订单？'))return;try{await api('/orders/'+o.id+'/cancel','POST');if(selected?.id===o.id)setSelected(null);await load()}catch(e){say((e as Error).message)}}}>取消</button></div>}{o.note&&<small>{o.note}</small>}</td></tr>)}</tbody></table></div>:<Empty text="还没有充值订单"/>}</Panel></>
}

function Usage(){const [rows,setRows]=useState<Row[]|null>(null),[error,setError]=useState('');useEffect(()=>{api<Row[]>('/usage').then(setRows).catch(e=>setError(e.message))},[]);return <><Notice>这里仅展示管理员核对后的消费，包含核对区间和更新时间。不是官方实时余额，不保存代码或对话内容。</Notice><Panel title="消费核对记录" caption="费用按核对时的官方账单录入。">{error?<p role="alert">{error}</p>:!rows?<p>正在读取记录…</p>:rows.length?<div className="table-wrap"><table><thead><tr><th>核对区间</th><th>模型</th><th>Token · 输入 / 输出</th><th>费用</th><th>核对时间</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.period_start)}<small>至 {date(r.period_end)}</small></td><td><code>{r.model}</code>{!!r.voided&&<small className="danger-text">已作废</small>}</td><td>{r.input_tokens.toLocaleString()} / {r.output_tokens.toLocaleString()}</td><td>{money(r.amount_fen)}</td><td>{date(r.checked_at)}</td></tr>)}</tbody></table></div>:<Empty text="尚未核对消费" detail="管理员核对官方用量后，记录会出现在这里。"/>}</Panel></>}


function Docs(){return <><Panel title="从安装到第一个项目" caption="配置完成后，重新打开一个终端窗口。"><div className="guide-section"><span className="guide-number">01</span><div><h3>打开你的项目文件夹</h3><p>在文件夹空白处右键，选择“在终端中打开”。</p><pre>claude</pre><p>启动后可以让助手解释代码、修改文件或执行测试。首次使用时按客户端提示确认项目权限。</p></div></div><div className="guide-section"><span className="guide-number">02</span><div><h3>给出一个具体的任务</h3><div className="prompt-example">帮我了解这个项目的结构，指出入口文件，然后解释它如何运行。</div><p>先从小任务开始，检查修改结果，再逐步增加范围。</p></div></div><div className="guide-section"><span className="guide-number">03</span><div><h3>通过 CC Switch 管理配置</h3><p>新装 CC Switch 首次启动会导入 Claude Code 配置；已有客户端需要确认助手打开的导入窗口。更换配置时保留自己的其他供应商。</p></div></div></Panel><div className="two-columns"><Panel title="常见问题"><details><summary>为什么提示 Key 无效？</summary><p>可能是 Key 已被管理员撤销或替换。请查看网站状态并联系管理员，替换后重新下载安装助手。</p></details><details><summary>为什么网站额度与官方不同？</summary><p>网站展示人工核对的账务记录。同一官方账号共享余额，网站不是实时计费网关。</p></details><details><summary>安装失败怎么办？</summary><p>查看助手显示的软件名称与失败步骤，确认能访问官方源后重试。票据过期需要重新下载。配置写入失败可使用自动备份恢复。</p></details></Panel><Panel title="官方资料"><a className="resource-link" href="https://api-docs.deepseek.com/guides/coding_agents/" target="_blank" rel="noreferrer">DeepSeek 客户端配置<ExternalLink size={17}/></a><a className="resource-link" href="https://code.claude.com/docs/en/setup" target="_blank" rel="noreferrer">Claude Code 安装说明<ExternalLink size={17}/></a><a className="resource-link" href="https://github.com/farion1231/cc-switch" target="_blank" rel="noreferrer">CC Switch 官方仓库<ExternalLink size={17}/></a></Panel></div></>}

function Admin({pub,say,copy,refreshPublic,initialTab,onNavigate}:{pub:Row;say:(s:string)=>void;copy:(s:string)=>Promise<void>;refreshPublic:()=>Promise<void>;initialTab:string;onNavigate:(tab:string)=>void}){
  const [tab,setTab]=useState(initialTab),[overview,setOverview]=useState<Row>({}),[rows,setRows]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]),[keys,setKeys]=useState<Row[]>([]),[providers,setProviders]=useState<Row[]>([]),[busy,setBusy]=useState(false),[newCode,setNewCode]=useState('');
  const tabs=[['keys','官方 Key 号池'],['orders','收款审核'],['users','账户管理'],['usage','消费核对'],['invites','邀请码'],['providers','渠道'],['settings','设置与公告'],['audits','操作记录']];
  useEffect(()=>{if(initialTab!==tab)setTab(initialTab)},[initialTab]);
  const currentTab=useRef(tab);currentTab.current=tab;
  const load=async()=>{const requested=currentTab.current;const [o,u,k,p]=await Promise.all([api('/admin/overview'),api<Row[]>('/admin/users'),api<Row[]>('/admin/keys'),api<Row[]>('/admin/providers')]);setOverview(o);setUsers(u.filter(x=>x.role==='student'));setKeys(k);setProviders(p);if(requested!=='settings'){const result=await api<Row[]>('/admin/'+requested);if(currentTab.current===requested)setRows(result)}};
  useEffect(()=>{setRows([]);load().catch(e=>say(e.message))},[tab]);
  const act=async(fn:()=>Promise<any>,message='操作已保存')=>{setBusy(true);try{const result=await fn();say(result?.message||message);await load();await refreshPublic();return result}catch(e){say((e as Error).message)}finally{setBusy(false)}};
  const form=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>};
  return <><div className="admin-stats">{[['学院成员',String(overview.users||0),Users],['待审核收款',String(overview.pending_orders||0),CreditCard],['待官网撤销',String(overview.pending_revocations||0),KeyRound],['已收服务费',money(overview.payments?.fee),ShieldCheck]].map(([label,value,Icon])=>{const I=Icon as typeof Users;return <div key={String(label)}><I size={20}/><span>{String(label)}</span><strong>{String(value)}</strong></div>})}</div><div className="admin-tabs">{tabs.map(([id,name])=><button className={id===tab?'selected':''} key={id} onClick={()=>{if(id!==tab){setRows([]);setTab(id);onNavigate(id)}}}>{name}</button>)}</div>
    {tab==='keys'&&<AdminKeyPool rows={keys} users={users} providers={providers} busy={busy} act={act} enabled={pub.key_delivery_enabled===true} refresh={load} say={say}/>}
    {tab==='orders'&&<Panel title="收款审核" caption="确认前请先检查微信或支付宝的真实到账。重复确认不会重复记账。">{rows.length?<div className="table-wrap"><table><thead><tr><th>用户 / 订单</th><th>支付金额</th><th>服务费 / 净额</th><th>方式</th><th>状态</th><th>审核</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.display_name}<small>{o.id}</small></td><td>{money(o.gross_fen)}</td><td>{money(o.fee_fen)} / {money(o.net_fen)}</td><td>{o.method==='wechat'?'微信':'支付宝'}</td><td>{status(o.status)}</td><td>{o.status==='submitted'&&<div className="table-actions"><Button className="small-button" busy={busy} onClick={()=>{if(confirm(`已核实 ${o.id} 到账 ${money(o.gross_fen)}？`))act(()=>api(`/admin/orders/${o.id}/review`,'POST',{action:'approve'}))}}>确认到账</Button><button className="text-link danger-text" disabled={busy} onClick={()=>{const note=prompt('驳回原因');if(note!==null)act(()=>api(`/admin/orders/${o.id}/review`,'POST',{action:'reject',note}))}}>驳回</button></div>}</td></tr>)}</tbody></table></div>:<Empty text="没有待审核订单"/>}</Panel>}
    {tab==='users'&&<AdminAccounts rows={rows} providers={providers} busy={busy} act={act}/>}
    {tab==='usage'&&<><Panel title="录入消费核对" caption="录入官方账单中的增量消费。同Key、同模型的核对时间段不能重叠。"><form className="form-grid" onSubmit={e=>{const f=form(e),k=keys.find(k=>k.id===Number(f.key_id));if(!k){say('请选择Key');return;}act(()=>api('/admin/usage','POST',{...f,user_id:k.owner_id,key_id:k.id,amount_fen:Math.round(Number(f.amount)*100),input_tokens:Number(f.input_tokens),output_tokens:Number(f.output_tokens),period_start:Math.floor(Date.parse(f.period_start)/1000),period_end:Math.floor(Date.parse(f.period_end)/1000)}))}}><label>用户与Key<select name="key_id" required>{keys.filter(k=>k.owner_id).map(k=><option value={k.id} key={k.id}>{k.display_name||k.username} · {k.masked}</option>)}</select></label><label>模型<input name="model" defaultValue="deepseek-flash" required/></label><label>核对区间开始<input type="datetime-local" name="period_start" required/></label><label>核对区间结束<input type="datetime-local" name="period_end" required/></label><label>费用（元）<input type="number" name="amount" min="0" step="0.01" required/></label><label>账单参考号<input name="reference" placeholder="唯一账单/核对编号" required/></label><label>输入 Token<input type="number" name="input_tokens" min="0" defaultValue="0"/></label><label>输出 Token<input type="number" name="output_tokens" min="0" defaultValue="0"/></label><Button className="primary" busy={busy} type="submit">保存人工核对</Button></form></Panel><Panel title="核对历史">{rows.length?<div className="table-wrap"><table><thead><tr><th>用户 / 模型</th><th>区间</th><th>费用</th><th>参考号</th><th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.username}<small>{r.model}</small></td><td>{date(r.period_start)}<small>至 {date(r.period_end)}</small></td><td>{money(r.amount_fen)}</td><td>{r.reference}</td><td>{r.voided?'已作废':<button className="text-link danger-text" disabled={busy} onClick={()=>{if(confirm('作废此核对记录并冲回账务？原始记录会保留。'))act(()=>api(`/admin/usage/${r.id}/void`,'POST'))}}>作废纠错</button>}</td></tr>)}</tbody></table></div>:<Empty/>}</Panel></>}
    {tab==='invites'&&<Panel title="邀请码" caption="完整邀请码仅在创建时显示，请保存并分享给熟人。" action={<Button className="primary" busy={busy} onClick={async()=>{const result=await act(()=>api('/admin/invites','POST',{max_uses:1}));if(result)setNewCode(result.code)}}><Plus size={16}/>创建单人邀请码</Button>}>{newCode&&<div className="new-invite"><code>{newCode}</code><button className="text-link" onClick={()=>copy(newCode)}><Clipboard size={15}/>复制</button><button className="icon-button" onClick={()=>setNewCode('')} aria-label="隐藏邀请码"><X size={16}/></button></div>}{rows.length?<div className="table-wrap"><table><thead><tr><th>编号 / 生成者</th><th>已用 / 可用次数</th><th>创建时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><code>{r.prefix}••••</code><small>{r.creator||'管理员'}</small></td><td>{r.used} / {r.max_uses}</td><td>{date(r.created_at)}</td><td>{r.enabled?'启用':'停用'}</td><td>{r.enabled===1&&<button className="text-link" onClick={()=>act(()=>api(`/admin/invites/${r.id}/disable`,'POST'))}>停用</button>}</td></tr>)}</tbody></table></div>:<Empty/>}</Panel>}
    {tab==='providers'&&<><Notice>首版只支持客户端直连的 Anthropic 兼容配置。新渠道管理能力默认“未经验证”；添加地址不会自动获得额度或撤销能力。</Notice><Panel title="供应商与中转渠道"><div className="provider-list">{rows.map(p=>{const cap=JSON.parse(p.capabilities);return <div key={p.id}><h3>{p.name}<span className="badge neutral">{p.kind==='deepseek'?'官方':'自定义'}</span></h3><code>{p.base_url}</code><p>模型 {p.model} · {cap.remote_revoke?'远程撤销':'人工撤销'} · {cap.independent_budget?'独立额度':'未验证独立额度'}</p></div>})}</div></Panel><Panel title="预留新渠道" caption="先在服务器的允许域名中加入供应商，再添加此配置。"><form className="form-grid" onSubmit={e=>{const f=form(e);act(()=>api('/admin/providers','POST',f))}}><label>名称<input name="name" required/></label><label>模型名称<input name="model" required/></label><label>Anthropic 基础地址<input type="url" name="base_url" placeholder="https://provider.example/anthropic" required/></label><label>模型列表核验地址<input type="url" name="models_url" placeholder="https://provider.example/v1/models" required/></label><Button className="primary" busy={busy}>添加渠道配置</Button></form></Panel></>}
    {tab==='settings'&&<><Panel title="网站与收款设置"><form className="form-grid" onSubmit={e=>act(()=>api('/admin/settings','POST',form(e)))}><label>平台名称<input name="site_name" defaultValue={pub.settings.site_name} required/></label><label>转账说明<input name="payment_note" defaultValue={pub.settings.payment_note}/></label><Button className="primary" busy={busy}>保存设置</Button></form><div className="qr-upload-grid">{[['wechat','微信'],['alipay','支付宝']].map(([id,name])=><div key={id}><h3>{name}收款码</h3>{pub.settings[id+'_qr']?<img src={pub.settings[id+'_qr']} alt={name+'收款码'}/>:<div className="qr-placeholder">尚未上传</div>}<label className="upload-button">上传 PNG / JPEG<input type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file){const fd=new FormData();fd.append('file',file);act(()=>api(`/admin/payment-qr/${id}`,'POST',fd))}e.target.value=''}}/></label></div>)}</div></Panel><Panel title="发布公告"><form className="form-grid" onSubmit={e=>act(()=>api('/admin/announcements','POST',form(e)))}><label>标题<input name="title" required/></label><label>内容<textarea name="content" rows={3} required/></label><Button className="primary" busy={busy}>发布公告</Button></form>{pub.announcements.map((n:Row)=><div className="announcement" key={n.id}><h3>{n.title}</h3><p>{n.content}</p><button className="text-link danger-text" onClick={()=>act(()=>api(`/admin/announcements/${n.id}/unpublish`,'POST'))}>撤下公告</button></div>)}</Panel></>}
    {tab==='audits'&&<Panel title="操作记录" caption="不记录密码、官方Key、安装票据或对话正文。">{rows.length?<div className="table-wrap"><table><thead><tr><th>时间</th><th>操作者</th><th>操作</th><th>目标 / 摘要</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.created_at)}</td><td>{r.username||'系统'}</td><td><code>{r.action}</code></td><td>{r.target}<small>{r.detail}</small></td></tr>)}</tbody></table></div>:<Empty/>}</Panel>}
  </>
}
